//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomSalca_E_Commerce_MVC_App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SlideImage
    {
        public int SlideID { get; set; }
        public string SlideTitle { get; set; }
        public string SlideImage { get; set; }
    }
}
